### ISSUE TITLE
player: 'segmentation fault' while trying to get metadata of a track

### ISSUE THREAD

**Issue by ArsenyZorin** [tizonia/tizonia-openmax-il#433]
Segmentation fault in tizonia while trying to get value of Metadata property with tizonia-remote. 
The same error while sending dbus query to org.mpris.MediaPlayer2.Player interface

```
-- This usually indicates a programming error in the crashing program and
-- should be reported to its vendor as a bug.
Jan 12 21:14:02 azorin systemd-coredump[13380]: Process 13018 (tizonia) of user 1000 dumped core.
                                                Stack trace of thread 13021:
                                                #0  0x00007f2a3e43483d __memset_avx2_erms (libc.so.6)
                                                #1  0x00007f2a3d1ab099 _dbus_string_insert_bytes (libdbus-1.so.3)
                                                #2  0x00007f2a3d195104 n/a (libdbus-1.so.3)
                                                #3  0x00007f2a3d19520f _dbus_type_writer_recurse (libdbus-1.so.3)
                                                #4  0x00007f2a3d199f9f dbus_message_iter_open_container (libdbus-1.so.3)
                                                #5  0x00007f2a3ed07c2c _ZN3Tiz4DBus11MessageIter11new_variantEPKc (libtizdbus
                                                #6  0x00007f2a3ed0ec75 _ZN3Tiz4DBuslsERNS0_11MessageIterERKNS0_7VariantE (lib
                                                #7  0x00007f2a3ed0cdff _ZN3Tiz4DBus17PropertiesAdaptor3GetERKNS0_11CallMessag
                                                #8  0x00007f2a3ed0e327 _ZNK3Tiz4DBus8CallbackINS0_17PropertiesAdaptorENS0_7Me
                                                #9  0x00007f2a3ed03707 _ZN3Tiz4DBus16InterfaceAdaptor15dispatch_methodERKNS0_
                                                #10 0x00007f2a3ed0ae37 _ZN3Tiz4DBus13ObjectAdaptor14handle_messageERKNS0_7Mes
                                                #11 0x00007f2a3ed08e32 _ZN3Tiz4DBus13ObjectAdaptor7Private21message_function_
                                                #12 0x00007f2a3d19e86b n/a (libdbus-1.so.3)
                                                #13 0x00007f2a3d18f056 dbus_connection_dispatch (libdbus-1.so.3)
                                                #14 0x00007f2a3ecfe878 _ZN3Tiz4DBus10Connection7Private11do_dispatchEv (libti
                                                #15 0x00007f2a3ed00a92 _ZN3Tiz4DBus10Dispatcher16dispatch_pendingERNSt7__cxx1
                                                #16 0x00007f2a3ed00b7f _ZN3Tiz4DBus10Dispatcher16dispatch_pendingEv (libtizdb
                                                #17 0x00007f2a3ed01f79 _ZN3Tiz4DBus13BusDispatcher12do_iterationEv (libtizdbu
                                                #18 0x00007f2a3ed01dc1 _ZN3Tiz4DBus13BusDispatcher5enterEv (libtizdbus-c++.so
                                                #19 0x000055acf88831d7 n/a (tizonia)
                                                #20 0x000055acf88835d0 n/a (tizonia)
                                                #21 0x00007f2a3f2a808c start_thread (libpthread.so.0)
                                                #22 0x00007f2a3e3d2e1f __clone (libc.so.6)
                                                Stack trace of thread 13047:
                                                #0  0x00007f2a3f2ae39d pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                #1  0x00007f2a3eac8a0f tiz_cond_wait (libtizplatform.so.0)
                                                #2  0x00007f2a3eac943b tiz_queue_receive (libtizplatform.so.0)
                                                #3  0x000055acf875665f n/a (tizonia)
                                                #4  0x00007f2a3f2a808c start_thread (libpthread.so.0)
                                                #5  0x00007f2a3e3d2e1f __clone (libc.so.6)
                                                Stack trace of thread 13085:
                                                #0  0x00007f2a3e3c891b __poll (libc.so.6)
                                                #1  0x00007f2a3835e773 n/a (libpulse.so.0)
                                                #2  0x00007f2a3834fbd0 pa_mainloop_poll (libpulse.so.0)
                                                #3  0x00007f2a38350271 pa_mainloop_iterate (libpulse.so.0)
                                                #4  0x00007f2a38350301 pa_mainloop_run (libpulse.so.0)
                                                #5  0x00007f2a3835e6ae n/a (libpulse.so.0)
                                                #6  0x00007f2a380fd81c n/a (libpulsecommon-11.1.so)
                                                #7  0x00007f2a3f2a808c start_thread (libpthread.so.0)
                                                #8  0x00007f2a3e3d2e1f __clone (libc.so.6)
                                                Stack trace of thread 13022:
                                                #0  0x00007f2a3f2ae39d pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                #1  0x00007f2a3eac8a0f tiz_cond_wait (libtizplatform.so.0)
                                                #2  0x00007f2a3eac943b tiz_queue_receive (libtizplatform.so.0)
                                                #3  0x00007f2a3e8ac97e n/a (libtizcore.so.0)
                                                #4  0x00007f2a3f2a808c start_thread (libpthread.so.0)
                                                #5  0x00007f2a3e3d2e1f __clone (libc.so.6)
                                                Stack trace of thread 13018:
                                                #0  0x00007f2a3e3c43d8 __read (libc.so.6)
                                                #1  0x00007f2a3e357528 _IO_file_underflow@@GLIBC_2.2.5 (libc.so.6)
                                                #2  0x00007f2a3e358672 _IO_default_uflow (libc.so.6)
                                                #3  0x00007f2a3e352bb8 _IO_getc (libc.so.6)
                                                #4  0x000055acf86d3ed3 n/a (tizonia)
                                                #5  0x000055acf86d3f9e n/a (tizonia)
                                                #6  0x000055acf86d730c n/a (tizonia)
                                                #7  0x000055acf86f65cb n/a (tizonia)
                                                #8  0x000055acf86e456a n/a (tizonia)
                                                #9  0x000055acf86e26cf n/a (tizonia)
                                                #10 0x000055acf86c73e4 n/a (tizonia)
                                                #11 0x00007f2a3e2fdf4a __libc_start_main (libc.so.6)
                                                #12 0x000055acf86d3aca n/a (tizonia)
                                                Stack trace of thread 13072:
                                                #0  0x00007f2a3f2ae39d pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                #1  0x00007f2a3eac8a0f tiz_cond_wait (libtizplatform.so.0)
                                                #2  0x00007f2a3eac943b tiz_queue_receive (libtizplatform.so.0)
                                                #3  0x00007f2a29cfde47 n/a (libtizonia.so.0)
                                                #4  0x00007f2a3f2a808c start_thread (libpthread.so.0)
                                                #5  0x00007f2a3e3d2e1f __clone (libc.so.6)
                                                Stack trace of thread 13083:
                                                #0  0x00007f2a3f2ae39d pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                #1  0x00007f2a3eac8a0f tiz_cond_wait (libtizplatform.so.0)
                                                #2  0x00007f2a3eac943b tiz_queue_receive (libtizplatform.so.0)
                                                #3  0x00007f2a29cfde47 n/a (libtizonia.so.0)
                                                #4  0x00007f2a3f2a808c start_thread (libpthread.so.0)
                                                #5  0x00007f2a3e3d2e1f __clone (libc.so.6)
                                                Stack trace of thread 13019:
                                                #0  0x00007f2a3e3d2f86 epoll_pwait (libc.so.6)
                                                #1  0x00007f2a3ead0149 n/a (libtizplatform.so.0)
                                                #2  0x00007f2a3eaced84 n/a (libtizplatform.so.0)
                                                #3  0x00007f2a3f2a808c start_thread (libpthread.so.0)
                                                #4  0x00007f2a3e3d2e1f __clone (libc.so.6)
                                                Stack trace of thread 13020:
                                                #0  0x00007f2a3f2ae39d pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                #1  0x00007f2a3eac8a0f tiz_cond_wait (libtizplatform.so.0)
                                                #2  0x00007f2a3eac943b tiz_queue_receive (libtizplatform.so.0)
                                                #3  0x000055acf8740977 n/a (tizonia)
                                                #4  0x00007f2a3f2a808c start_thread (libpthread.so.0)
                                                #5  0x00007f2a3e3d2e1f __clone (libc.so.6)
                                                Stack trace of thread 13084:
                                                #0  0x00007f2a3f2ae39d pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                #1  0x00007f2a3eac8a0f tiz_cond_wait (libtizplatform.so.0)
                                                #2  0x00007f2a3eac943b tiz_queue_receive (libtizplatform.so.0)
                                                #3  0x00007f2a29cfde47 n/a (libtizonia.so.0)
                                                #4  0x00007f2a3f2a808c start_thread (libpthread.so.0)
                                                #5  0x00007f2a3e3d2e1f __clone (libc.so.6)
-- Subject: Process 13018 (tizonia) dumped core
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
--
-- Process 13018 (tizonia) crashed and dumped core.
```

Tizonia was compiled from aur package 'tizonia-all' on ArchLinux
Tizonia version:
```
tizonia 0.11.0. Copyright (C) 2017 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>
```

**Comment by tizonia** [comment]
Hi!,

Thanks for taking the time to upload the stack traces. That's really useful!.

Yes, I think I've known about this issue for some time. At the time when I saw this, I thought it was related to the third-party library libdbus-cplusplus. 

I had recently embedded this dbus library into the project so I sounds like I will need to spend some time to see if I can find a fix the library (or find the issue somewhere else in the Tizonia player code).

**Comment by tizonia** [comment]
Here is another backtrace of the crash:

{code}
hread 4 "mprismgr" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffebff1700 (LWP 32655)]
__memset_erms () at ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:141
141	../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S: No such file or directory.
(gdb) bt
#0  __memset_erms () at ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:141
#1  0x00007ffff454c0f8 in _dbus_string_insert_bytes () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#2  0x00007ffff45369be in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#3  0x00007ffff4536abf in _dbus_type_writer_recurse () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#4  0x00007ffff453b6cc in dbus_message_iter_open_container () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#5  0x00007ffff624322c in Tiz::DBus::MessageIter::new_variant (this=0x7fffebfefc00, sig=0x7fffebfefa40 "") at message.cpp:278
#6  0x00007ffff624ecab in Tiz::DBus::operator<< (iter=..., val=...) at types.cpp:83
#7  0x00007ffff624d2e7 in Tiz::DBus::PropertiesAdaptor::Get (this=0x7fffebff0a20, call=...) at property.cpp:71
#8  0x00007ffff624dad0 in Tiz::DBus::Callback<Tiz::DBus::PropertiesAdaptor, Tiz::DBus::Message, Tiz::DBus::CallMessage const&>::call (
    this=0x7fffdc0072b0, param=...) at ../include/dbus-c++/util.h:283
#9  0x00007ffff623be37 in Tiz::DBus::Slot<Tiz::DBus::Message, Tiz::DBus::CallMessage const&>::call (this=0x7fffdc0073d0, param=...)
    at ../include/dbus-c++/util.h:252
#10 0x00007ffff623ad04 in Tiz::DBus::InterfaceAdaptor::dispatch_method (this=0x7fffebff0a20, msg=...) at interface.cpp:64
#11 0x00007ffff624536c in Tiz::DBus::ObjectAdaptor::handle_message (this=0x7fffebff0aa8, msg=...) at object.cpp:225
#12 0x00007ffff6244922 in Tiz::DBus::ObjectAdaptor::Private::message_function_stub (dmsg=0x7fffdc003950, data=0x7fffebff0aa8)
    at object.cpp:92
#13 0x00007ffff453fd20 in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#14 0x00007ffff4530aea in dbus_connection_dispatch () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#15 0x00007ffff6231276 in Tiz::DBus::Connection::Private::do_dispatch (this=0x7fffdc000d10) at connection.cpp:132
#16 0x00007ffff6234c29 in Tiz::DBus::Dispatcher::dispatch_pending (this=0x555556481d80, pending_queue=std::__cxx11::list = {...})
    at dispatcher.cpp:236
#17 0x00007ffff6234a45 in Tiz::DBus::Dispatcher::dispatch_pending (this=0x555556481d80) at dispatcher.cpp:198
#18 0x00007ffff6238f7c in Tiz::DBus::BusDispatcher::do_iteration (this=0x555556481d80) at eventloop-integration.cpp:148
#19 0x00007ffff6238c2a in Tiz::DBus::BusDispatcher::enter (this=0x555556481d80) at eventloop-integration.cpp:100
#20 0x0000555555d4a7d4 in tiz::control::mprismgr::dispatch_cmd (p_mgr=0x55555647dd20, p_cmd=0x555556459150)
    at mpris/tizmprismgr.cpp:291
#21 0x0000555555d49854 in tiz::control::thread_func (p_arg=0x55555647dd20) at mpris/tizmprismgr.cpp:106
#22 0x00007ffff67fc6db in start_thread (arg=0x7fffebff1700) at pthread_create.c:463
#23 0x00007ffff589e88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
{code}
