### ISSUE TITLE
Updating Instructions threw an unhandled exception, seems like a syntax error

### ISSUE THREAD

**Issue by connorAhearn** [tizonia/tizonia-openmax-il#520]
### Description

Summed up mostly by title, 

### Steps to Reproduce

Self explanatory, in next bit

**Expected behavior:** 
I enter this in command line, as repo describes
sudo -H pip install --upgrade gmusicapi soundcloud youtube-dl pafy pycountry titlecase pychromecast plexapi fuzzywuzzy eventlet && sudo -H pip install git+https://github.com/plamere/spotipy.git --upgrade

and it should update all the packages for the application

**Actual behaviour:** 
pi@raspberrypi:~ $ sudo -H pip install --upgrade gmusicapi soundcloud youtube-dl pafy pycountry titlecase pychromecast plexapi fuzzywuzzy eventlet && sudo -H pip install git+https://github.com/plamere/spotipy.git --upgrade
Collecting gmusicapi
Collecting soundcloud
  Using cached https://files.pythonhosted.org/packages/68/f2/b6ddd262786f3a31db342ad223feebb9774e4809672106b9cfc9b4798d87/soundcloud-0.5.0-py2-none-any.whl
Collecting youtube-dl
  Using cached https://files.pythonhosted.org/packages/c4/b9/0f3483b83ddb226538d91e0ac9713ef7d5ee7b4d13d4c631ef027a36f6a1/youtube_dl-2018.10.5-py2.py3-none-any.whl
Collecting pafy
  Using cached https://files.pythonhosted.org/packages/b0/e8/3516f761558525b00d3eaf73744eed5c267db20650b7b660674547e3e506/pafy-0.5.4-py2.py3-none-any.whl
Collecting pycountry
  Using cached https://files.pythonhosted.org/packages/18/99/a81f1da10070c563450a4ef334622e72fb0b7b74c929fdbed711154d8416/pycountry-18.5.26-py2-none-any.whl
Collecting titlecase
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'

**Reproduces how often:** 
Only tried it once

### Versions

0.15.0

### Installation Method Used

curl in command line

**Comment by tizonia** [comment]
Hi!, thanks for taking the time.

```
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
```

I've googled this and some people appear to attribute this issue to a temporary dodgy network connection or perhaps to an outdated pip installation.

Which OS and pip version are you running?

I usually do this to upgrade 'pip' on my machines:
```
$ sudo -H pip install --upgrade pip
```

**Comment by tizonia** [comment]
Closing, since this does not seem to be an issue that we can fix in Tizonia.
