### ISSUE TITLE
Problems accessing Google Play Music

### ISSUE THREAD

**Issue by hashborgir** [tizonia/tizonia-openmax-il#546]
Installed via repository, it can't read any config file in any location.
Removed.
Installed via snap, it can't read any config file in any location.

I've tried:

$HOME/snap/tizonia/current/.config/tizonia/tizonia.conf
$HOME/.config/tizonia/tizonia.conf
/etc/xdg/tizonia/tizonia.conf

No matter what you specify in either the snap's version's config file or the distro packaged version's config file, it will simply not read any configuration data at all.

Extremely frustrating. Documentation is broken and terrible.  Configuration file: 'tizonia.conf'

Tizonia creates its config file in one of the following locations when it
first starts (add your user credentials here):
    - Debian or AUR packages: $HOME/.config/tizonia/tizonia.conf
    - Snap package: $HOME/snap/tizonia/current/.config/tizonia/tizonia.conf

Example configuration files may also be found at 
    - /etc/xdg/tizonia/tizonia.conf or 
    - /snap/tizonia/current/etc/xdg/tizonia/tizonia.conf.

None of these work. I've put the correct information in every single file location and no version of tizonia will read any config. It keeps saying:

$  tizonia --gmusic-unlimited-feeling-lucky-station

Need to provide a Google Play Music user name.

I have in the files: 

$HOME/.config/tizonia/tizonia.conf
$HOME/snap/tizonia/current/.config/tizonia/tizonia.conf

gmusic.user       = 'my_username@gmail.com'
gmusic.password   = 'my_password'
gmusic.device_id  = 'my_deviceid'

When I specify everything on command line I get:

[Google Play Music] [Authenticating] : 'with user credentials'
[Google Play Music] [Station search in Google Play Music] : 'I'm Feeling Lucky'. 
[Google Play Music] [Station] 'I'm Feeling Lucky'.
[Google Play Music] [Station] 'Ellen Once Again'.
[Google Play Music] [Station] 'I'm Just a Lucky So and So'.
[Google Play Music] [Station] 'Popa Chubby'.
[Google Play Music] [Station] 'I'm Feelin' Lucky'.
[Google Play Music] [Track] 'Names' by 'Klangstof'.
[Google Play Music] [Tracks in queue] '100'.
[Google Play Music] (KeyError) : 'sessionToken'

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]

**Comment by juanrubio** [comment]
Hi! Sorry to hear that you are experiencing some issues.

I would like to help you but you need to explain how you concluded that the config file is not being read. 

Which service are you trying to configure?. And what is your OS?

**Comment by hashborgir** [comment]
Yes.

**Comment by tizonia** [comment]
@hashborgir 

I've changed the subject because tizonia.conf is being correctly read in your case (as you are getting the list of the stations and songs being added to the queue).

I've tested both the 0.16.0 Snap package (Ubuntu 16.04 32-bit) and the deb-based install (Ubuntu 18.04 64-bit) using two Google accounts, one free tier account and one paid subscription. In all four scenarios, Google Play music is accessed correctly and stations/songs are retrieved and played back without problems. On both tests, I've used an Android device id.

So there must be something else going on in your case which makes your scenario different from those four scenarios.

I need to know:
- Type of install (snap or deb)
- Tizonia version (`tizonia --version` and `snap info tizonia` if snap install)
- The version of gmusicapi if deb install (`pip show gmusicapi`)

**Comment by hashborgir** [comment]
Changing the subject doesn't magically make the config loaded. 

Both, snap and deb.
stable:    0.16.0

Name: gmusicapi
Version: 11.1.1

The config is not being read. The config is not being read because I have to specify the username and device on the command line. Without specifying username and device on the command line, and the correct info exists in all possible config files, it still won't read my username or device id from the config.

Since it seems like you're not really wanting to help solve the issue, but just pass the buck, I'm done now. Have fun. 

Let's change the subject line and tizonia should magically start to read all configs!

**Comment by tizonia** [comment]
> Extremely frustrating. Documentation is broken and terrible
> Or you have trouble with reading/comprehension and might need to go back to remedial English classes
> Having to deal with arrogant developers is far worse than having to use crap software.

Honestly, I don't think you are being very respectful here. 

Still, I would like to help you. If you have a problem with the software, I would like to try and fix it. But you need to bear with me.

Here is a logging configuration file. 
[log4c.tar.gz](https://github.com/tizonia/tizonia-openmax-il/files/2737627/log4c.tar.gz)

If you extract it on your $HOME directory (`tar xf log4c.tar.gz`), you should end up with the file $HOME/.log4crc

With that file there, Tizonia will output to the console the messages of the module that read the configuration file. This should help us troubleshoot the issue on your environment. It would great if you could post here the console output (please replace usernames/passwords with dummy values).

**Comment by tizonia** [comment]
@hashborgir 

Thanks for uploading the logs. The issue you are experiencing is the same as #468:

```
key-value pair : [ gmusic.user       = 'username@gmail.com']
```

So you should be able to use Google Music as long as you remove the space characters at the beginning or at the end of the line above. Also no need for ' characters.

```
key-value pair : [gmusic.user = username@gmail.com]
```

Let me know if this finally works for you.

P.S.: I renamed the issue because I read your original message before you edited it to add the info that you were adding also the credentials on the command-line.

**Comment by hashborgir** [comment]
It reads the config and shows the key-value pair without any spaces, however now it gives this error.

```
[stdout] 09-01-2019 22:55:21.295 - [PID:24736][TID:24736] [DEBUG] [tiz.platform.rc] [tizrc.c:tiz_rcfile_init:704] --- Loading [/home/stoned/.config/tizonia/tizonia.conf] rc file succeeded
[stdout] 09-01-2019 22:55:21.295 - [PID:24736][TID:24736] [TRACE] [tiz.platform.rc] [tizrc.c:tiz_rcfile_get_value:741] --- Retrieving value for Key [gmusic.user] in section [tizonia]
[stdout] 09-01-2019 22:55:21.295 - [PID:24736][TID:24736] [TRACE] [tiz.platform.rc] [tizrc.c:tiz_rcfile_get_value:741] --- Retrieving value for Key [gmusic.password] in section [tizonia]
[stdout] 09-01-2019 22:55:21.295 - [PID:24736][TID:24736] [TRACE] [tiz.platform.rc] [tizrc.c:tiz_rcfile_get_value:741] --- Retrieving value for Key [gmusic.device_id] in section [tizonia]
tizonia 0.16.0. Copyright (C) 2018 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

[stdout] 09-01-2019 22:55:21.296 - [PID:24736][TID:24736] [TRACE] [tiz.platform.rc] [tizrc.c:tiz_rcfile_get_value:741] --- Retrieving value for Key [mpris-enabled] in section [tizonia]
[stdout] 09-01-2019 22:55:21.296 - [PID:24736][TID:24739] [TRACE] [tiz.platform.rc] [tizrc.c:tiz_rcfile_get_value:741] --- Retrieving value for Key [enabled] in section [resource-management]
[stdout] 09-01-2019 22:55:21.296 - [PID:24736][TID:24739] [TRACE] [tiz.platform.rc] [tizrc.c:tiz_rcfile_get_value_list:775] --- Retrieving value list for Key [component-paths] in section [il-core]
[stdout] 09-01-2019 22:55:21.296 - [PID:24736][TID:24739] [TRACE] [tiz.platform.rc] [tizrc.c:tiz_rcfile_get_value_list:775] --- Retrieving value list for Key [component-paths] in section [il-core]

tizonia exiting (OMX_ErrorComponentNotFound).

 Unable to verify the component list.
```

**Comment by hashborgir** [comment]
I tried to reinstall tizonia, and now I get the following:

```
[Google Play Music] [Track] 'I Killed You In The Morning' by 'Foreign Fields'.
[Google Play Music] [Track] 'All We Need' by 'Fyfe'.
[Google Play Music] [Track] '6am & Do It Again' by 'Dark Rooms'.
[Google Play Music] [Track] 'Roses On Your Dress' by 'Flora Cash'.
[Google Play Music] [Track] 'Great Wave' by 'Mimicking Birds'.
[Google Play Music] [Track] 'Sadness Is Taking Over' by 'Flora Cash'.
[Google Play Music] [Track] 'Lavender Burning' by 'Half Waif'.
[Google Play Music] [Track] 'Choir' by 'Perfume Genius'.
[Google Play Music] [Track] 'Everything Apart' by 'Foxwarren'.
[Google Play Music] [Track] 'Waiting (10 Years)' by 'Low Roar'.
[Google Play Music] [Track] 'Galapagos' by 'Yuno'.
[Google Play Music] [Track] 'Ahimsa' by 'Peter Silberman'.
[Google Play Music] [Tracks in queue] '100'.
[Google Play Music] (KeyError) : 'sessionToken'

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]
```

**Comment by tizonia** [comment]
Thanks. 
```
[Google Play Music] (KeyError) : 'sessionToken'
```
I believe I have seen this error once before, but I can't remember how. To troubleshoot this issue, I will need some more logs. This time we will need to add this to the terminal before running Tizonia:
```
export TIZONIA_GMUSICPROXY_DEBUG=1
```
Also, please upgrade your 'gmusicapi'. Version 12.0.0 has been released in the last few hours. 
```
sudo -H pip install --upgrade gmusicapi
```

**Comment by tizonia** [comment]
@hashborgir 

Is this issue still bothering you?

**Comment by juanrubio** [comment]
Closing this issue now since there's been no activity for a month. Please re-open if you have any other evidence.

**Comment by vidurb** [comment]
Hi juanrubio. I found this googling for a solution to something else, but I experienced a problem similar to this so I thought I'd let you know in case it helped - I found my issue was that I'd added my tizonia.conf to my dotfiles repo, but I had added the one from the .deb and then switched to the snap install - the config that came with the snap install used environment variables for the location of the libraries, whereas the config from the .deb package had the path to the libraries hardcoded. I managed to fix it myself, but hopefully my experience might help you? If not, sorry to reopen this, and many thanks for a very useful alternative to heavy GUI applications.

**Comment by jadacyrus** [comment]
Hi, I am also seeing this issue. It appears to only happen when trying to use `--gmusic-unlimited-*` commands. As in `--gmusic-playlist` works just fine.

Here is the error:
```
...
[Google Play Music] [Tracks in queue] '100'.
[Google Play Music] (KeyError) : 'sessionToken'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tizgmusicproxy.py", line 1054, in next_url
    url = self._retrieve_track_url(next_song)
  File "/usr/lib/python3/dist-packages/tizgmusicproxy.py", line 1162, in _retrieve_track_url
    song["id"], song["wentryid"], song["sessionToken"], self.device_id
KeyError: 'sessionToken'

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]
```

gmusicapi version: `13.0.0`
tizonia version:
```
aurcioli@aurcioli-workstation-debian:~/.config/tizonia$ dpkg -l | grep tizonia
ii  libtizonia0                              0.22.0-1                            amd64        Tizonia's OpenMAX IL 1.2 base component library, run-time library
ii  tizonia-all:amd64                        0.22.0-1                            amd64        Tizonia command-line music player (metapackage)
ii  tizonia-config                           0.22.0-1                            amd64        Tizonia command-line music player (config files)
ii  tizonia-player                           0.22.0-1                            amd64        Tizonia command-line music player
```

**Comment by juanrubio** [comment]
Hopefully, this has been fixed with @jadacyrus PR
https://github.com/tizonia/tizonia-openmax-il/pull/758
