### ISSUE TITLE
Update command failed

### ISSUE THREAD

**Issue by britus** [tizonia/tizonia-openmax-il#611]
# Issue Template
4f2a9f5d19b014ad3164fbbc8513ef27a7bbe1e6c5e3 (from https://pypi.org/simple/zeroconf/), version 0.17.6 doesn't match >=0.17.7
  Using version 0.23.0 (newest of versions: 0.23.0, 0.22.0, 0.21.3, 0.21.3, 0.21.2, 0.21.2, 0.21.1, 0.21.1, 0.21.0, 0.21.0, 0.20.0, 0.20.0, 0.19.1, 0.19.1, 0.19.0, 0.19.0, 0.18.0, 0.18.0, 0.17.7, 0.17.7)
  Downloading zeroconf-0.23.0.tar.gz
  Downloading from URL https://files.pythonhosted.org/packages/d7/25/8bbdd4857820e0cdc380c7e0c3543dc01a55247a1d831c712571783e74ec/zeroconf-0.23.0.tar.gz#sha256=e0c333b967c48f8b2e5cc94a1d4d28893023fb06dfd797ee384a94cdd1d0eef5 (from https://pypi.org/simple/zeroconf/)
  Running setup.py (path:/tmp/pip-build-oiwUZR/zeroconf/setup.py) egg_info for package zeroconf
    error in zeroconf setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in zeroconf setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-oiwUZR/zeroconf
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-oiwUZR/zeroconf

### Description

Command failue:
sudo -H pip install --upgrade gmusicapi soundcloud youtube-dl pafy pycountry titlecase pychromecast plexapi fuzzywuzzy eventlet && sudo -H pip install git+https://github.com/plamere/spotipy.git --upgrade

### Steps to Reproduce
call
sudo -H pip install --upgrade gmusicapi soundcloud youtube-dl pafy pycountry titlecase pychromecast plexapi fuzzywuzzy eventlet && sudo -H pip install git+https://github.com/plamere/spotipy.git --upgrade

**Expected behavior:** [What you expect to happen]
work

**Actual behaviour:** [What actually happens]
don't work

**Reproduces how often:** [What percentage of the time does it reproduce?]
always

### Versions
tizonia 0.13.0. Copyright (C) 2018 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

### Installation Method Used

Bintray debs

### Additional Information

wishes: work

**Comment by britus** [comment]
Dep version failed - fixed
