### ISSUE TITLE
Not able to cast from penguin terminal to chromecast

### ISSUE THREAD

**Issue by srpayo** [tizonia/tizonia-openmax-il#639]
Hi,

I am trying to cast from my chromebook (Asus c434) to my chromecast while using Tizonia installed in the penguin terminal. Everything seems to load fine and then it just hangs forever. I am guessing it might be something related to network ports in the crostini container? Playing locally in the chromebook via the same terminal works just fine.

example command:
user@penguin:~$ tizonia --youtube-audio-search 'florence + the machine' --cast 'Living Room TV'

user@penguin:~$ tizonia --version
tizonia 0.18.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

user@penguin:~$ netstat -anlp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:5355            0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:2222            0.0.0.0:*               LISTEN      -                   
tcp        1      1 100.115.92.197:40252    172.217.168.238:443     LAST_ACK    -                   
tcp        0      0 100.115.92.197:2222     100.115.92.25:40864     ESTABLISHED -                   
tcp        1      1 100.115.92.197:43778    216.58.208.110:443      LAST_ACK    -                   
tcp6       0      0 :::5355                 :::*                    LISTEN      -                   
tcp6       0      0 :::2222                 :::*                    LISTEN      -                   
udp        0      0 127.0.0.53:53           0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:68              0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:5355            0.0.0.0:*                           -                   
udp6       0      0 :::5355                 :::*                                -

**Comment by srpayo** [comment]
I think it might be the same issue as https://github.com/tizonia/tizonia-openmax-il/issues/483 since I can see similar errors. I also tried the following commands: 

user@penguin:~$ tizonia --youtube-audio-search 'florence + the machine' -c 'emk.cc.livingroomtv'
user@penguin:~$ tizonia --youtube-audio-search 'florence + the machine' -c '192.168.178.12'

same results:

YouTube] [Streams in queue] '150'.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/tizyoutubeproxy.py", line 274, in obtain_stream
    video = pafy.new(stream['i'].ytid)
  File "/usr/local/lib/python2.7/dist-packages/pafy/pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts=ydl_opts)
  File "/usr/local/lib/python2.7/dist-packages/pafy/backend_youtube_dl.py", line 31, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pafy/backend_shared.py", line 97, in __init__
    self._fetch_basic()
  File "/usr/local/lib/python2.7/dist-packages/pafy/backend_youtube_dl.py", line 40, in _fetch_basic
    self._ydl_info = ydl.extract_info(self.videoid, download=False)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 2201, in _real_extract
    upload_date = unified_strdate(upload_date)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 2852, in unified_strdate
    upload_date = datetime.datetime.strptime(date_str, expression).strftime('%Y%m%d')
AttributeError: 'module' object has no attribute '_strptime'

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/tizyoutubeproxy.py", line 274, in obtain_stream
    video = pafy.new(stream['i'].ytid)
  File "/usr/local/lib/python2.7/dist-packages/pafy/pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts=ydl_opts)
  File "/usr/local/lib/python2.7/dist-packages/pafy/backend_youtube_dl.py", line 31, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pafy/backend_shared.py", line 97, in __init__
    self._fetch_basic()
  File "/usr/local/lib/python2.7/dist-packages/pafy/backend_youtube_dl.py", line 40, in _fetch_basic
    self._ydl_info = ydl.extract_info(self.videoid, download=False)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 2201, in _real_extract
    upload_date = unified_strdate(upload_date)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 2852, in unified_strdate
    upload_date = datetime.datetime.strptime(date_str, expression).strftime('%Y%m%d')
AttributeError: 'module' object has no attribute '_strptime'

   FlorenceMachineVEVO : Florence + The Machine - Hunger
     YouTube Id : 5GHXEGz3PJg
     Duration : 04m:31s
     File Format : webm
     Bitrate : 160k
     Size : 4 MiB
     View Count : 37254456
     Description : Celebrate the 10 year anniversary of Lungs with special edition re-release on August 16th - https://FATM.lnk.to/Lungs10 Officia
     Published : 2018-05-03 18:35:00

**tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_renderer.chromecast:port:0]
 [OMX_ErrorInsufficientResources]**

**Comment by tizonia** [comment]
Hi!, thanks for stopping by and raising a defect.

This is a genuine issue. The Chromecast functionality in Tizonia has been a bit neglected in recent releases. The pychromecast library that Tizonia depends on was migrated to Python3 some time ago. But Tizonia has not migrated to Python 3 until just now, in version 0.19.0.

So now it is a good moment to re-align the Chromecast functionality. Hopefully, this issue will get fixed in the next release, 0.20.0.

**Comment by tizonia** [comment]
Hi @srpayo 

I'm closing this issue for now. The Chromecast functionality has been revived in 0.20.0. It is not perfect yet, but at least it is usable (a few issues remain).

Please give it a try and see how if it works for you.
