### ISSUE TITLE
Unable to use for machine without audio devices, workaround failed as well

### ISSUE THREAD

**Issue by evilmtv** [tizonia/tizonia-openmax-il#677]
### Description

There are no hardware sound cards/devices available as it is a cloud server that I'm testing this out on. As such I've created a dummy hardware device using `sudo modprobe snd-dummy` for Alsa.
Trying to stream a Spotify song gives this error:
```bash
tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_renderer.alsa.pcm:port:0]
 [OMX_ErrorInsufficientResources]
```
I'm not sure if its because of my setup or I've wrongly configured `~/.config/spotifyd/spotifyd.conf`.
Or is there a cleaner way to do this by tinkering with the source code itself and allowing for no audio output?

### Steps to Reproduce

```bash
# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 1: Dummy [Dummy], device 0: Dummy PCM [Dummy PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7 
```

Config file: 
```bash
[plugins]
# OpenMAX IL Component plugins section

# Each key-value pair represents a list of any data that a
# specific component might need. The entries here must honor the following
# format: OMX.component.name.key = <semi-colon-separated list of items>

# ALSA Audio Renderer
# -------------------------------------------------------------------------
#
# OMX.Aratelia.audio_renderer.alsa.pcm.preannouncements_disabled.port0 = false
OMX.Aratelia.audio_renderer.alsa.pcm.alsa_device = Dummy
OMX.Aratelia.audio_renderer.alsa.pcm.alsa_mixer = Dummy PCM


[tizonia]
# Tizonia player section

# The default audio renderer used by the tizonia player
# -------------------------------------------------------------------------
# Valid values are:
# - OMX.Aratelia.audio_renderer.pulseaudio.pcm
# - OMX.Aratelia.audio_renderer.alsa.pcm
default-audio-renderer = OMX.Aratelia.audio_renderer.alsa.pcm
```
Did I name the device and mixer wrongly?

**Expected behavior:** Able to play into the void

**Actual behaviour:** Doesn't play into the void :(

**Reproduces how often:** 100%

### Versions

```bash
# docker-tizonia --version
tizonia 0.18.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

# docker-tizonia --debug
tizonia 0.18.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

Debug Info:
            * [Boost 1_65_1]
            * [TagLib 1.11.1]
            * [MediaInfoLib - v17.12]
```

```bash
# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### Installation Method Used

Docker

### Additional Information

Note: Running as root instead of a normal user. This gave problems with PulseAudio leaving me with Alsa. Tried to run in both desktop (RDP) and ssh.

**Comment by evilmtv** [comment]
Update:

Used a proper user account (as opposed to root), got PulseAudio working but still getting the same error.

```bash
$ sudo docker-tizonia --spotify-track-id spotify:track:0xPHALeBb3aLEZrj0T0R2P
tizonia 0.18.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

[Spotify] [Connecting] : 'REDACTED'.
[Spotify] [Track id] 'spotify:track:0xPHALeBb3aLEZrj0T0R2P'.
[Spotify] [Track] 'Sayonara Memory' [7!!].
[Spotify] [Tracks in queue] '1'.
[Spotify] [Cache]: '/var/tmp/tizonia-tizonia-spotify-REDACTED'
[Spotify] [Login] 'REDACTED' logged in.
[Spotify] [Connected] : 'spotify:track:0xPHALeBb3aLEZrj0T0R2P'.

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_renderer.pulseaudio.pcm:port:0]
 [OMX_ErrorInsufficientResources]
```

```bash
$ pacmd list-sinks | grep -e 'name:' -e 'index:'
    index: 0
        name: <alsa_output.platform-snd_dummy.0.analog-mono>
    index: 1
        name: <GAME>
  * index: 2
        name: <MUSIC>
```

settings shown are default: `.config/tizonia/tizonia.conf`
```bash
# ALSA Audio Renderer
# -------------------------------------------------------------------------
#                                                                                                                                                                                                                                     # OMX.Aratelia.audio_renderer.alsa.pcm.preannouncements_disabled.port0 = false
OMX.Aratelia.audio_renderer.alsa.pcm.alsa_device = default
OMX.Aratelia.audio_renderer.alsa.pcm.alsa_mixer = Master
[tizonia]
# Tizonia player section
# The default audio renderer used by the tizonia player
# -------------------------------------------------------------------------
# Valid values are:
# - OMX.Aratelia.audio_renderer.pulseaudio.pcm
# - OMX.Aratelia.audio_renderer.alsa.pcm
default-audio-renderer = OMX.Aratelia.audio_renderer.pulseaudio.pcm
```

Same error when set to alsa's output in PulseAudio default sink setting
```bash
$ pacmd list-sinks | grep -e 'name:' -e 'index:'
  * index: 0
        name: <alsa_output.platform-snd_dummy.0.analog-mono>
    index: 1
        name: <GAME>
    index: 2
        name: <MUSIC>
```

**Comment by tizonia** [comment]
Hi @evilmtv!

Thanks for taking the time to report issues.

Do you have a `null` PCM?. 

From `aplay`'s man page:
```    -L, --list-pcms
              List all PCMs defined
```
This is the output of `aplay -L` on my system:
```
default
    Playback/recording through the PulseAudio sound server
null
    Discard all samples (playback) or generate zero samples (capture)

```
I think `null` is what you would need to add to your config (maybe the naming convention is confusing):

```
OMX.Aratelia.audio_renderer.alsa.pcm.alsa_device = null
```

**Comment by evilmtv** [comment]
Update 2:

Went down the rabbit hole.

Tried to rebuild the docker image using the `Dockerfile` here https://hub.docker.com/r/tizonia/docker-tizonia/dockerfile 
Had to update mopidy stuff as stated here tizonia/tizonia-openmax-il#670 
But still to no avail.

Finally gave in and decided to build the recommended way using
```
curl -kL https://github.com/tizonia/tizonia-openmax-il/raw/master/tools/install.sh | bash
```
and it works with the exact same config, both youtube and spotify could stream.

Not sure what's up with the docker method though, feeling really annoyed. I'll try to figure out whats wrong over the next few days.

Anyone with a desktop (with proper sound device working) able to test the docker method?

**Comment by evilmtv** [comment]
Might have found the issue and partial solution.

`sudo` causes the issue
i.e. `sudo docker-tizonia --spotify-track-id ....`

After allowing docker to be run as non-root user as instructed here: https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user
I was able to run `docker-tizonia --spotify-track-id ....` without `sudo` and it could play spotify music with no issues.

Additional issue:
Youtube playback was not working in both your docker image and after i partially edited and rebuilt it, with or without sudo. No issues with the 'recommended way' one.
```bash
$ docker-tizonia --youtube-audio-mix-search "Queen Official"
tizonia 0.18.0. Copyright (C) 2019 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1378, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1291, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1354, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[YouTube] (IOError) : ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1378, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1291, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1354, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]
```

I'll try a clean VM and redo this (just removing sudo from the docker command) without setting up any of the audio stuff and see how exactly what other issues I had to solve.
Also I'll see if I can update your `Dockerfile` [here](https://hub.docker.com/r/tizonia/docker-tizonia/dockerfile) to match the current [install.sh](https://github.com/tizonia/tizonia-openmax-il/blob/master/tools/install.sh)

Btw here's the output for `aplay -L`
```bash
$ aplay -L
default
    Playback/recording through the PulseAudio sound server
null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
sysdefault:CARD=Dummy
    Dummy, Dummy PCM
    Default Audio Device
dmix:CARD=Dummy,DEV=0
    Dummy, Dummy PCM
    Direct sample mixing device
dsnoop:CARD=Dummy,DEV=0
    Dummy, Dummy PCM
    Direct sample snooping device
hw:CARD=Dummy,DEV=0
    Dummy, Dummy PCM
    Direct hardware device without any conversions
plughw:CARD=Dummy,DEV=0
    Dummy, Dummy PCM
    Hardware device with all software conversions
```
I guess audio probably wasn't the issue all along.

**Comment by tizonia** [comment]
@evilmtv 

Thanks for digging into this. 

I should mention that the docker-tizonia repo has fallen one version behind the most recent version of Tizonia.

Tizonia is currently at version 0.19.0, which included the migration to Python 3. docker-tizonia is still at version 0.18.0 (Python 2).

Let's move this issue to the docker-tizonia repo.
