### ISSUE TITLE
error in mint tricia when spotify commands are ran

### ISSUE THREAD

**Issue by TeslaXT** [tizonia/tizonia-openmax-il#708]
### Tizonia crashes when spotify commands are run ###
*****************************************************************************************************************
Traceback (most recent call last):
  File "<string>", line 2, in <module>
AttributeError: module 'importlib' has no attribute 'util'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_tizonia.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
AttributeError: module 'importlib' has no attribute 'util'

Python modules 'spotifyapi' or 'fuzzywuzzy' not found.
Please make sure these are installed correctly.

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.spotify.pcm:port:0]
 [OMX_ErrorInsufficientResources]
*********************************************************************************************
### Steps to Reproduce

1. install using the curl script on linux mint Linux Mint 19.3 Tricia x86_64 
2. attempt to run a spotify command

**Expected behavior:**successful login and music plays

**Actual behaviour:** errors out with above error

**Reproduces how often:** 100 percent 6 attempts

### Versions

tizonia 0.21.0. Copyright (C) 2020 Juan A. Rubio and contributors
This software is part of the Tizonia project <https://tizonia.org>

* [Linux@5.3.0-45-generic-#37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020]
	    * [Boost 1_65_1]
	    * [TagLib 1.11.1]
	    * [MediaInfoLib - v17.12]

please help also please see issue #703 if you can help there also

**Comment by TeslaXT** [comment]
this also throws issues with youtube

[Youtube] [Connecting] : 'https://www.youtube.com/playlist?list=PLpQAUTzfNGx8m861Nis_I7vzy5gjgXwBf'.
Traceback (most recent call last):
  File "<string>", line 2, in <module>
AttributeError: module 'importlib' has no attribute 'util'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_tizonia.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
AttributeError: module 'importlib' has no attribute 'util'

Python modules 'pafy', 'youtube-dl' or 'fuzzywuzzy' not found.
Please make sure these are installed correctly.

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]



on top of this i have also attempted to install via snap but it does the following

originah@OriginPC:~$ sudo snap install tizonia
tizonia 0.18.0 from Tizonia installed
originah@OriginPC:~$ tizonia --help
bash: /usr/bin/tizonia: No such file or directory
originah@OriginPC:~$

**Comment by tizonia** [comment]
Hi @TeslaXT !

Thanks for reporting. Always useful.

> AttributeError: module 'importlib' has no attribute 'util'

This tells me that the python interpreter being instantiated when Tizonia runs on your distro is the Python 2 interpreter. 

Tizonia does not support Python 2 anymore, so this error is expected. 

The question is, why is Python 2 being used on your distro (Linux Mint 19.3 Tricia x86_64 ?) when Tizonia is requesting Python 3?

**Comment by TeslaXT** [comment]
No idea why this is happening but I will fix that straight away. Fresh install so must have missed that :/ thankyou i will feedback when fixed

**Comment by TeslaXT** [comment]
The question is, why is Python 2 being used on your distro (Linux Mint 19.3 Tricia x86_64 ?) when Tizonia is requesting Python 3?

No idea why I had 2 installed quickly stepped up to the latest python install and tizonia works a treat thankyou so much I love this as my goto player !!!

**Comment by tizonia** [comment]
Happy to hear that it is now working for you! 

Thanks for using the software.
