### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by fcwoknhenuxdfiyv** [tizonia/tizonia-openmax-il#785]
There hasn't been much activity for a while and installation is broken because bintray is gone. So, is this project dead?

**Comment by mmischitelli** [comment]
curious to know as well

**Comment by 23ewrdtf** [comment]
Would like to know too.

1. Can't update
2. Log folder /var/log/tizonia/ is empty. Can't find any log config.
3. Getting an error due to YT changing their dislike button.

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/tizyoutubeproxy.py", line 413, in obtain_stream
    audio = video.getbestaudio(preftype="webm")
  File "/usr/local/lib/python3.7/dist-packages/pafy/backend_shared.py", line 386, in getbestaudio
    if not self.audiostreams:
  File "/usr/local/lib/python3.7/dist-packages/pafy/backend_shared.py", line 176, in audiostreams
    self._process_streams()
  File "/usr/local/lib/python3.7/dist-packages/pafy/backend_youtube_dl.py", line 81, in _process_streams
    self._fetch_basic()
  File "/usr/local/lib/python3.7/dist-packages/pafy/backend_youtube_dl.py", line 54, in _fetch_basic
    self._dislikes = self._ydl_info['dislike_count']
KeyError: 'dislike_count'
```

**Comment by juanrubio** [comment]
Hi all,

Thanks for your interest. The project isn't really dead. Just a major lack of free time over the last year or so, the plan is to come back to it and get the major issues fixed.

One of the first things that will be needed is new a hosting service that can provide the same functionality as Bintray. That means primarily the ability to upload and host Debian packages that have been built elsewhere. There are some build services out there that would provide both the building and the hosting, but there are some challenges with building Tizonia in those places (e.g. Tizonia has some Python build-time dependencies that aren't easy to satisfy in some cloud build services).

**Comment by Josh5** [comment]
Can tizonia be built with gitlab actions?

**Comment by 23ewrdtf** [comment]
> Can tizonia be built with gitlab actions?

If yes, I'm happy to help with that. I use Gitlab a lot.

**Comment by dreirund** [comment]
> *So, is this project dead?*

I just emailed some comitters which I could get from the `git log` directly and asked about the status, since the project _still_ did not receive updates and has several [build errors](https://github.com/tizonia/tizonia-openmax-il/issues) with updated libraries and compiler versions (in some cases even directly includable fixes were submitted but not included yet).

Regards!
